services:
  web:
    image: node:20.9.0
    working_dir: /web  
    volumes:
      - ../web:/web
    ports:
      - 3000:3000
    command: bash -c "npm install && npm run dev"

  api:
    image: node:20.9.0
    working_dir: /api
    volumes:
      - ../api:/api
    ports:
      - 10000:10000
    command: bash -c "npm install && npm start"
      
  db:
    image: mysql
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ../data/mysql/datafile:/var/lib/mysql
      - ../data/mysql/mysql-files:/var/lib/mysql-files
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: cryptodb